# traefik.toml dynamic config (mostly TLS)
# dynamic config in the static config file will be ignored
[tls]
[tls.options.default]
minVersion = "VersionTLS12"
cipherSuites = [
  "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
  "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
  "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
  "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
]

[tls.stores.default.defaultGeneratedCert]
resolver = "letsencrypt"

[tls.stores.default.defaultGeneratedCert.domain]
main = "longs.stat.berkeley.edu"
